### ISSUE TITLE
Resolution of outputs

### ISSUE THREAD

**Issue by b03902128** [tatsy/tf-generative#1]
Hi, 

Thanks for the great implementation!

I ran CVAE-GAN on CelebA dataset for 20 epochs.
The resolution of output png seems correct and the conditions are making effects (see attachment), while the results looks blurry and noisy. 

I also checked CVAE and the results have similar issues.
I believe the results should look better, I'm thinking if there is something wrong about the data pre/post-processing.
Or maybe I miss something?

Thanks in advance:)  

![epoch_0020_batch_200000](https://user-images.githubusercontent.com/22385143/39793202-0aa6690e-5377-11e8-92ab-ff7ad1250f7e.png)

**Comment by ZLKong** [comment]
Hi, 

I ran the command: 
python train.py --model=cvaegan --dataset datasets/files/celebA.hdf5  --epoch=200 --batchsize=100 --output=output

But I got an error :  tensorflow.python.framework.errors_impl.InternalError: Failed to create session.
Do you know how to fix it?


Traceback (most recent call last):
  File "train.py", line 82, in <module>
    tf.app.run(main)
  File "/media/smilelab/Black6TB/anaconda2/envs/tensorflow_CVAE/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 68, in main
    resume=args.resume
  File "/media/smilelab/Black6TB/zhenglun/tf-generative-master/models/cvaegan.py", line 187, in __init__
    super(CVAEGAN, self).__init__(input_shape=input_shape, name=name, **kwargs)
  File "/media/smilelab/Black6TB/zhenglun/tf-generative-master/models/base.py", line 243, in __init__
    super(CondBaseModel, self).__init__(**kwargs)
  File "/media/smilelab/Black6TB/zhenglun/tf-generative-master/models/base.py", line 48, in __init__
    self.sess = tf.Session()
  File "/media/smilelab/Black6TB/anaconda2/envs/tensorflow_CVAE/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1494, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/media/smilelab/Black6TB/anaconda2/envs/tensorflow_CVAE/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 626, in __init__
    self._session = tf_session.TF_NewSession(self._graph._c_graph, opts)
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.
